DROP TABLE IF EXISTS KOA_TODO;
CREATE TABLE KOA_TODO (
  todoId INT NOT NULL AUTO_INCREMENT,
  todoItem VARCHAR(300) NOT NULL,
  startTime DATETIME NOT NULL,
  endTime DATETIME NOT NULL,
  isComplete BOOLEAN DEFAULT FALSE,
  userId INT NOT NULL,
  PRIMARY KEY(todoId),
  FOREIGN KEY(userId) REFERENCES KOA_BLOG_USER(userId)
)