CREATE TABLE KOA_BLOG_USER
(
  userId INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(40) NOT NULL,
  password VARCHAR(16) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  phoneNumber VARCHAR(11) NOT NULL,
  PRIMARY KEY (userId)
);