DROP TABLE IF EXISTS KOA_BLOG_TAGS;
CREATE TABLE KOA_BLOG_TAGS
(
  tagId INT NOT NULL AUTO_INCREMENT,
  tagName VARCHAR(40) NOT NULL,
  userId INT NOT NULL,
  articalNumber INT DEFAULT 0,
  PRIMARY KEY(tagId),
  FOREIGN KEY(userId) REFERENCES KOA_BLOG_USER(userId)
);
INSERT INTO KOA_BLOG_TAGS (tagName,userId) VALUES('测试标签',3);