DROP TABLE IF EXISTS KOA_BLOG_FILE;
CREATE TABLE KOA_BLOG_FILE
(
  fileId INT NOT NULL AUTO_INCREMENT,
  fileName TINYTEXT NOT NULL,
  publishDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  fileBrief TEXT DEFAULT NULL,
  authorId INT NOT NULL,
  location TEXT NOT NULL,
  downloadNumber INT DEFAULT 0,
  PRIMARY KEY (fileId),
  FOREIGN KEY(authorId) REFERENCES KOA_BLOG_USER(userId)
);