DROP TABLE IF EXISTS KOA_BLOG_CONTENT;
CREATE TABLE KOA_BLOG_CONTENT
(
  blogId INT NOT NULL AUTO_INCREMENT,
  blogName VARCHAR(40) NOT NULL,
  publishDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  lastUpdateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
  blogContent BLOB DEFAULT NULL,
  authorId INT NOT NULL,
  PRIMARY KEY (blogId),
  FOREIGN KEY(authorId) REFERENCES KOA_BLOG_USER(userId)
);